# Generated by Django 3.2.6 on 2021-10-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmpModel',
            fields=[
                ('pmp_model_nm', models.CharField(db_column='PMP_MODEL_NM', max_length=50, primary_key=True, serialize=False)),
                ('pmp_type', models.CharField(blank=True, db_column='PMP_TYPE', max_length=50, null=True)),
                ('bore', models.CharField(blank=True, db_column='BORE', max_length=50, null=True)),
                ('create_dt', models.DateTimeField(blank=True, db_column='CREATE_DT', null=True)),
            ],
            options={
                'db_table': 'pmp_model',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('site_id', models.CharField(db_column='SITE_ID', max_length=50, primary_key=True, serialize=False)),
                ('site_nm', models.CharField(blank=True, db_column='SITE_NM', max_length=50, null=True)),
                ('site_addr', models.CharField(blank=True, db_column='SITE_ADDR', max_length=50, null=True)),
                ('manu_comp_nm', models.CharField(blank=True, db_column='MANU_COMP_NM', max_length=50, null=True)),
                ('manu_comp_phone', models.CharField(blank=True, db_column='MANU_COMP_PHONE', max_length=50, null=True)),
                ('deli_comp_nm', models.CharField(blank=True, db_column='DELI_COMP_NM', max_length=50, null=True)),
                ('deli_comp_phone', models.CharField(blank=True, db_column='DELI_COMP_PHONE', max_length=50, null=True)),
                ('manu_dt', models.DateTimeField(blank=True, db_column='MANU_DT', null=True)),
                ('free_srv_st_dt', models.DateTimeField(blank=True, db_column='FREE_SRV_ST_DT', null=True)),
                ('free_srv_end_dt', models.DateTimeField(blank=True, db_column='FREE_SRV_END_DT', null=True)),
                ('paid_srv_comp_nm', models.CharField(blank=True, db_column='PAID_SRV_COMP_NM', max_length=50, null=True)),
                ('paid_srv_comp_phone', models.CharField(blank=True, db_column='PAID_SRV_COMP_PHONE', max_length=50, null=True)),
                ('create_dt', models.DateTimeField(blank=True, db_column='CREATE_DT', null=True)),
            ],
            options={
                'db_table': 'site_info',
            },
        ),
        migrations.CreateModel(
            name='SitePmp',
            fields=[
                ('pmp_manu_num', models.CharField(db_column='PMP_MANU_NUM', max_length=50, primary_key=True, serialize=False)),
                ('pmp_model_nm', models.CharField(db_column='PMP_MODEL_NM', max_length=50)),
                ('pmp_type', models.CharField(blank=True, db_column='PMP_TYPE', max_length=50, null=True)),
                ('bore', models.CharField(blank=True, db_column='BORE', max_length=50, null=True)),
                ('head', models.CharField(blank=True, db_column='HEAD', max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, db_column='CAPACITY', max_length=50, null=True)),
                ('create_dt', models.DateTimeField(blank=True, db_column='CREATE_DT', null=True)),
                ('site_id', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_pmp_site_id', to='app_qr.siteinfo')),
            ],
            options={
                'db_table': 'site_pmp',
            },
        ),
        migrations.CreateModel(
            name='PmpRepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_engineer_nm', models.CharField(blank=True, db_column='VISIT_ENGINEER_NM', max_length=50, null=True)),
                ('visit_engineer_phone', models.CharField(blank=True, db_column='VISIT_ENGINEER_PHONE', max_length=50, null=True)),
                ('repair_contents', models.CharField(blank=True, db_column='REPAIR_CONTENTS', max_length=50, null=True)),
                ('visit_date', models.DateTimeField(blank=True, db_column='VISIT_DATE', null=True)),
                ('create_dt', models.DateTimeField(blank=True, db_column='CREATE_DT', null=True)),
                ('pmp_manu_num', models.ForeignKey(db_column='PMP_MANU_NUM', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmp_repair_history_pmp_manu_num', to='app_qr.sitepmp')),
                ('site_id', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmp_repair_history_site_id', to='app_qr.sitepmp')),
            ],
            options={
                'db_table': 'pmp_repair_history',
            },
        ),
    ]
